# Docker-compose for monitoring stack of  Watt project
services:
  name: ${COMPOSE_PROJECT_NAME}
  alertmanager:
    image: "prom/alertmanager:v0.28.0"
    container_name: ${ALERTMGR_CONTAINER_NAME}
    environment:
      - HTTPS_METHOD=noredirect
    ports:
      - "9093:9093"
    labels:
      NAME: "alertmanager"
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - "./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      - "alertmanager-data:/alertmanager"
    networks:
      - network-monitoring
    restart: always
    command:
      - "--log.level=debug"
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
  grafana:
    image: "grafana/grafana:11.4.0"
    container_name: ${GRAFANA_CONTAINER_NAME}
    environment:
      - GF_SERVER_HTTP_PORT=9094
      - HTTPS_METHOD=noredirect
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    restart: unless-stopped
    ports:
      - "9094:9094"
    labels:
      NAME: "grafana"
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./config/grafana/provisioning:/etc/grafana/provisioning" #Add the configuration
      - "./config/grafana/provisioning/dashboards:/var/lib/grafana/dashboards" #Add the Dashboard
    networks:
      - network-monitoring
  prometheus:
    image: "prom/prometheus:v3.1.0"
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    environment:
      - HTTPS_METHOD=noredirect
    ports:
      - "9095:9095"
    restart: always
    labels:
      NAME: "prometheus"
      ENVIRONMENT: ${ENVIRONMENT}
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:9095"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME}"
    volumes:
      - "prometheus-data:/prometheus"
      - "./config/prometheus:/etc/prometheus"
    networks:
      - network-monitoring
  pushgateway:
    image: "prom/pushgateway:v1.5.0"
    container_name: ${PUSHGATEWAY_CONTAINER_NAME}
    environment:
      - HTTPS_METHOD=noredirect
    ports:
      - "9096:9096"
    labels:
      NAME: "pushgateway"
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - "pushgateway-data:/pushgateway"
    networks:
      - network-monitoring
    restart: always
    command:
      - "--web.listen-address=:9096"
      - "--persistence.file=/pushgateway/metrics.pb"
networks:
  stelog-monitoring:
    driver: bridge
volumes:
  grafana-data:
  prometheus-data:
  alertmanager-data:
  pushgateway-data:
