global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "monitoring@stelog.com"
  smtp_auth_username: "your-gmail@gmail.com"
  smtp_auth_password: "your-app-password"
  smtp_require_tls: true

route:
  receiver: "support-team-email"
  group_by: [alertname]

receivers:
  - name: "support-team-email"
    email_configs:
      - to: "example@example.com"
